"""Deferred affine + phase backend for the boundary-free active regime.

For circuits whose ACTIVE op stream contains only
    EXPAND(+diagonal) / CNOT / MULTI_CNOT / CZ / MULTI_CZ / T / S / RZ(ROT)
    / Z-basis measurement / SWAP   (no H, U2, U4, or X-basis measurement),
the active state is exactly

    |psi> = sum_x e^{i f(x)} phi(x) |A x>

with phi a PRODUCT of equatorial single-qubit states (so |phi(x)|^2 is uniform),
A an affine GF(2) map (from CNOT), f a diagonal phase polynomial (from T/RZ/CZ).
Z-basis outcome probabilities do not depend on f, so the entire measurement
record is generated by:
  * a fresh uniform source bit per active ident at EXPAND,
  * an affine GF(2) map carried symbolically through CNOT/MULTI_CNOT,
  * each Z measurement = parity of the (already-sampled) source bits, then the
    SAME frame/sign/readout-noise record assembly as the tensor backend.

No tensor, no QR, no bond -> O(k) integer ops per gate. The frame/noise/dormant/
readout branches are kept identical to TTNBackend.run_shot so the measurement
record DISTRIBUTION matches. A non-diagonal op (H / U2 / U4 / interfere) raises
BoundaryEncountered: those circuits must use the tensor backend.
"""
from __future__ import annotations

import numpy as np

from mdam.frame import treewidth as T_mod
from mdam.frame import frame_layer as ds_mod

_FLAG_SIGN = ds_mod.FLAG_SIGN


class BoundaryEncountered(Exception):
    """Raised when a non-diagonal active op forces tensor materialization."""


class AffineActiveBackend:
    def __init__(self, spec):
        self.spec = spec
        self.step_to_ident_expand = {}
        for ident, lc in spec["lifecycle"].items():
            self.step_to_ident_expand[lc["promote_step"]] = ident

    def _reset(self):
        self.frame = ds_mod.PauliFrame()
        self.record = {}
        self.slot2id = {}
        self.bits = {}          # ident -> int bitmask over source-bit indices
        self.srcval = 0         # int bitmask: bit s set => source bit s sampled 1
        self.next_src = 0
        self.n_cnot = 0         # affine XOR updates (the "work" we did instead of QR)

    def _parity(self, mask):
        return bin(mask & self.srcval).count("1") & 1

    def run_shot(self, prog, seed, max_steps=None):
        rng = np.random.default_rng(seed)
        self._reset()
        total = len(prog)
        run_steps = total if max_steps is None else min(total, int(max_steps))
        noise_sampler = ds_mod.ClifftNoiseSampler(prog, rng)

        for step in range(run_steps):
            inst = prog[step]
            name = T_mod._opname(inst.opcode)
            if name in ds_mod.IGNORE_OPS:
                continue
            a1 = int(inst.axis_1); a2 = int(inst.axis_2)
            flags = int(getattr(inst, "flags", 0))
            sign = 1 if (flags & _FLAG_SIGN) else 0

            # ---- frame-only Clifford (identical to tensor backend) ----
            if name == "OP_FRAME_H":      self.frame.h(a1); continue
            if name in ("OP_FRAME_S", "OP_FRAME_S_DAG"): self.frame.s_gate(a1); continue
            if name == "OP_FRAME_CNOT":   self.frame.cnot(a1, a2); continue
            if name == "OP_FRAME_CZ":     self.frame.cz(a1, a2); continue
            if name == "OP_FRAME_SWAP":   self.frame.swap(a1, a2); continue

            # ---- noise / conditional Pauli (identical) ----
            if name == "OP_APPLY_PAULI":
                d = ds_mod._d(inst); cond = d.get("condition_idx"); mask = d.get("cp_mask_idx")
                if cond is not None and mask is not None and int(self.record.get(int(cond), 0)) == 1:
                    ds_mod._apply_cp_mask(prog, int(mask), self.frame, rng)
                continue
            if name == "OP_NOISE":
                d = ds_mod._d(inst); site = d.get("noise_site_idx")
                if site is not None:
                    ds_mod._apply_noise_site(prog, int(site), self.frame, rng, noise_sampler)
                continue
            if name == "OP_NOISE_BLOCK":
                d = ds_mod._d(inst)
                start = d.get("start_site", d.get("noise_site_idx", d.get("block_idx")))
                count = d.get("count", 1)
                if start is not None:
                    for s in range(int(start), int(start) + int(count)):
                        ds_mod._apply_noise_site(prog, s, self.frame, rng, noise_sampler)
                continue
            if name == "OP_READOUT_NOISE":
                d = ds_mod._d(inst); entry_idx = d.get("readout_noise_idx")
                entries = getattr(prog, "readout_noise", None)
                if entry_idx is not None and entries is not None:
                    entry = entries[int(entry_idx)]
                    meas_idx = int(entry["meas_idx"])
                    if float(rng.random()) < float(entry["prob"]):
                        self.record[meas_idx] = int(self.record.get(meas_idx, 0)) ^ 1
                continue

            # ---- dormant measurements (identical) ----
            if name in ("OP_MEAS_DORMANT_STATIC", "OP_MEAS_DORMANT_STATIC_FORCED"):
                d = ds_mod._d(inst); cidx = int(d.get("classical_idx", 0))
                self.record[cidx] = self.frame.xb(a1) ^ sign
                continue
            if name in ("OP_MEAS_DORMANT_RANDOM", "OP_MEAS_DORMANT_RANDOM_FORCED"):
                d = ds_mod._d(inst); cidx = int(d.get("classical_idx", 0))
                m_abs = int(rng.integers(0, 2))
                self.record[cidx] = m_abs ^ sign
                self.frame.set_xz(a1, m_abs, 0)
                continue

            # ---- EXPAND family: fresh uniform source bit (diagonal phase ignored) ----
            if name in ("OP_EXPAND", "OP_EXPAND_T", "OP_EXPAND_T_DAG", "OP_EXPAND_ROT"):
                ident = self.step_to_ident_expand.get(step)
                if ident is None:
                    continue
                self.slot2id[a1] = ident
                s = self.next_src; self.next_src += 1
                self.bits[ident] = 1 << s
                if int(rng.integers(0, 2)):
                    self.srcval |= (1 << s)
                continue

            # ---- diagonal phase ops: irrelevant to Z outcomes ----
            if name in ("OP_PHASE_T", "OP_PHASE_T_DAG", "OP_PHASE_ROT",
                        "OP_ARRAY_T", "OP_ARRAY_T_DAG", "OP_ARRAY_ROT"):
                continue
            if name in ("OP_ARRAY_S", "OP_ARRAY_S_DAG"):
                self.frame.s_gate(a1)     # frame part kept; state phase dropped
                continue

            # ---- non-diagonal single-axis: cannot defer ----
            if name in ("OP_ARRAY_H", "OP_ARRAY_U2"):
                raise BoundaryEncountered(f"{name} at step {step}")

            # ---- two-axis ----
            if name == "OP_ARRAY_CNOT":          # a1 = control, a2 = target
                u = self.slot2id.get(a1); v = self.slot2id.get(a2)
                if u is not None and v is not None:
                    self.bits[v] = self.bits.get(v, 0) ^ self.bits.get(u, 0)
                    self.n_cnot += 1
                self.frame.cnot(a1, a2)
                continue
            if name == "OP_ARRAY_CZ":            # diagonal (phase) -> bits unchanged
                self.frame.cz(a1, a2)
                continue
            if name == "OP_ARRAY_MULTI_CNOT":    # a1 = target, mask = controls
                d = ds_mod._d(inst)
                tgt_slot = a1; tgt = self.slot2id.get(tgt_slot)
                for ctrl_slot in ds_mod._bits(int(d["mask"])):
                    if ctrl_slot == tgt_slot:
                        continue
                    c = self.slot2id.get(ctrl_slot)
                    if tgt is not None and c is not None:
                        self.bits[tgt] = self.bits.get(tgt, 0) ^ self.bits.get(c, 0)
                        self.n_cnot += 1
                    self.frame.cnot(ctrl_slot, tgt_slot)
                continue
            if name == "OP_ARRAY_MULTI_CZ":      # diagonal -> bits unchanged
                d = ds_mod._d(inst)
                for tgt_slot in ds_mod._bits(int(d["mask"])):
                    if tgt_slot == a1:
                        continue
                    self.frame.cz(a1, tgt_slot)
                continue
            if name == "OP_ARRAY_U4":
                raise BoundaryEncountered(f"OP_ARRAY_U4 at step {step}")

            # ---- active Z measurement: outcome = parity of source bits ----
            if name in ("OP_MEAS_ACTIVE_DIAGONAL", "OP_MEAS_ACTIVE_DIAGONAL_FORCED"):
                d = ds_mod._d(inst); cidx = int(d.get("classical_idx", 0))
                ident = self.slot2id.get(a1)
                if ident is None:
                    continue
                b = self._parity(self.bits.get(ident, 0))
                del self.slot2id[a1]
                self.bits.pop(ident, None)         # keep srcval: it may feed others
                m_abs = b ^ self.frame.xb(a1)
                self.record[cidx] = m_abs ^ sign
                self.frame.set_xz(a1, m_abs, 0)
                continue
            if name in ("OP_MEAS_ACTIVE_INTERFERE", "OP_MEAS_ACTIVE_INTERFERE_FORCED",
                        "OP_SWAP_MEAS_INTERFERE", "OP_SWAP_MEAS_INTERFERE_FORCED"):
                raise BoundaryEncountered(f"{name} at step {step}")

            # ---- SWAP: relabel slot->ident, frame swap (bits keyed by ident) ----
            if name == "OP_ARRAY_SWAP":
                i1 = self.slot2id.get(a1); i2 = self.slot2id.get(a2)
                if i1 is not None: del self.slot2id[a1]
                if i2 is not None: del self.slot2id[a2]
                if i1 is not None: self.slot2id[a2] = i1
                if i2 is not None: self.slot2id[a1] = i2
                self.frame.swap(a1, a2)
                continue
            # anything else unknown: ignore (matches tensor backend fall-through)
        return self.record

    def sample(self, prog, shots, seed=None, num_measurements=None):
        master = np.random.default_rng(seed)
        if num_measurements is None:
            num_measurements = prog.num_measurements
        out = np.zeros((shots, num_measurements), dtype=np.uint8)
        for sh in range(shots):
            sd = int(master.integers(0, 2**63 - 1))
            rec = self.run_shot(prog, sd)
            for cidx, bit in rec.items():
                if 0 <= cidx < num_measurements:
                    out[sh, cidx] = bit
        return out
